version: '3.8'

services:
  backend:
    build: ./backend
    container_name: svvdevel_backend
    restart: unless-stopped
    ports:
      - "8001:8080"
    environment:
      - DB_PATH=/app/data/database.db
    volumes:
      - ./backend/data:/app/data
      - ./backend/uploads:/app/uploads
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: svvdevel_frontend
    restart: unless-stopped
    ports:
      - "3001:80"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: svvdevel_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
